'use client'

import { useRef } from "react"
import { motion, useInView } from "framer-motion"
import { cn } from "@/lib/utils"

const tools = [
  {
    id: "stop-loss",
    name: "Stop Loss Analyzer",
    tag: "Risk Management",
    tagAccent: false,
    featured: true,
    description:
      "Downloads live price data, calculates ATR and RSI, and suggests position-sized stop-loss levels at three risk tolerances. An AI layer adds commentary from the market context.",
    detail:
      "The most technically demanding tool in the set. Combines quantitative technical analysis with LLM-generated risk narrative — the kind of output a Bloomberg terminal gives you, but built from scratch.",
    tech: ["Python", "yfinance", "Plotly", "n8n AI Agent"],
    href: "https://cfo-portfolio-cx6sumrbrr5etsa64hqym3.streamlit.app/Stop_Loss_Analyzer",
    status: "Live",
  },
  {
    id: "investment-committee",
    name: "Investment Committee",
    tag: "Due Diligence",
    tagAccent: true,
    featured: false,
    description:
      "Three-agent system: a Bull analyst, a Bear analyst, and a CFO synthesizer. Each reads the same data and argues their case. The CFO role assigns a confidence score and risk verdict — then validates every claim against live SEC EDGAR filings.",
    detail: null,
    tech: ["Python", "Streamlit", "SEC EDGAR API", "fpdf2", "Multi-agent"],
    href: "https://investment-committee-aortlctmpqtpa4gpkrjg6t.streamlit.app/",
    status: "Live",
  },
  {
    id: "ai-analyst",
    name: "AI Analyst",
    tag: "Research",
    tagAccent: false,
    featured: false,
    description:
      "Enter any ticker. Receive a structured research memo — business overview, recent catalysts, risks, and valuation context — generated by an n8n AI research agent.",
    detail: null,
    tech: ["Python", "n8n Webhook", "LLM Research Agent"],
    href: "https://cfo-portfolio-cx6sumrbrr5etsa64hqym3.streamlit.app/AI_Analyst",
    status: "Live",
  },
  {
    id: "daily-briefing",
    name: "Daily Briefing",
    tag: "Intelligence",
    tagAccent: false,
    featured: false,
    description:
      "Gemini 2.0 synthesises the last 24 hours of supply chain and AI news into a structured brief. Three editorial tones: CFO exec summary, LinkedIn post, or technical deep dive.",
    detail: null,
    tech: ["Python", "Google Gemini 2.0 Flash", "Search Grounding"],
    href: "https://cfo-portfolio-cx6sumrbrr5etsa64hqym3.streamlit.app/Daily_Briefing",
    status: "Live",
  },
]

export function CFOTools() {
  const ref = useRef<HTMLElement>(null)
  const isInView = useInView(ref, { once: true, margin: "-100px" })

  const featured = tools.find((t) => t.featured)!
  const secondary = tools.filter((t) => !t.featured)

  return (
    <section
      id="tools"
      ref={ref}
      className="relative py-32 lg:py-48 overflow-hidden"
      style={{ background: "#0B0D10" }}
    >
      {/* Cool blue-tinted radial — visually distinct from other sections */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_80%_20%,rgba(100,130,200,0.05)_0%,transparent_60%)] pointer-events-none" />
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_20%_80%,rgba(200,169,110,0.04)_0%,transparent_60%)] pointer-events-none" />

      <div className="container mx-auto px-6 lg:px-12">

        {/* Header */}
        <div className="grid lg:grid-cols-12 gap-12 mb-14">
          <div className="hidden lg:block lg:col-span-2">
            <motion.div
              initial={{ opacity: 0, x: -20 }}
              animate={isInView ? { opacity: 1, x: 0 } : {}}
              transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
              className="sticky top-32"
            >
              <div className="w-8 h-px bg-accent mb-4" />
              <p className="font-mono text-[11px] text-muted-foreground tracking-[0.25em] uppercase">
                03 · CFO Tools
              </p>
            </motion.div>
          </div>

          <div className="lg:col-span-10">
            {/* Mobile label */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.6 }}
              className="flex items-center gap-3 lg:hidden mb-6"
            >
              <div className="w-6 h-px bg-accent" />
              <p className="font-mono text-[11px] text-accent tracking-[0.3em] uppercase">CFO Tools</p>
            </motion.div>

            <div className="space-y-5 max-w-3xl">
              <motion.h2
                initial={{ opacity: 0, y: 30 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.9, ease: [0.16, 1, 0.3, 1] }}
                className="font-cormorant font-light text-[clamp(2.8rem,6vw,5rem)] text-foreground leading-[1.05] tracking-[-0.01em]"
              >
                Tools I built
                <br />
                <span className="italic text-accent">because they didn&rsquo;t exist.</span>
              </motion.h2>

              <motion.p
                initial={{ opacity: 0, y: 20 }}
                animate={isInView ? { opacity: 1, y: 0 } : {}}
                transition={{ duration: 0.8, delay: 0.15, ease: [0.16, 1, 0.3, 1] }}
                className="font-sans text-muted-foreground text-lg leading-relaxed"
              >
                Applied financial tools built with Python, Streamlit, and LLMs.
                Each one solves a specific problem I had as a CFO that off-the-shelf
                software handled poorly or not at all.
              </motion.p>
            </div>
          </div>
        </div>

        {/* Tool layout */}
        <div className="grid lg:grid-cols-12 gap-12">
          <div className="lg:col-span-2" /> {/* spacer */}
          <div className="lg:col-span-10 space-y-4">

            {/* Featured card — Stop Loss Analyzer */}
            <motion.div
              initial={{ opacity: 0, y: 40 }}
              animate={isInView ? { opacity: 1, y: 0 } : {}}
              transition={{ duration: 0.9, delay: 0.2, ease: [0.16, 1, 0.3, 1] }}
              className="group relative border border-[rgba(200,169,110,0.12)] hover:border-[rgba(200,169,110,0.3)] transition-all duration-500 overflow-hidden"
              style={{ background: "#0E1014" }}
            >
              {/* Featured glow */}
              <div className="absolute top-0 right-0 w-64 h-64 bg-[radial-gradient(circle,rgba(200,169,110,0.06)_0%,transparent_70%)] pointer-events-none" />

              <div className="p-8 lg:p-10 grid lg:grid-cols-2 gap-8 lg:gap-12">
                <div className="space-y-5">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-[10px] text-accent tracking-[0.25em] uppercase border border-[rgba(200,169,110,0.3)] px-2.5 py-1 rounded-sm">
                      {featured.tag}
                    </span>
                    <span className="font-mono text-[10px] text-muted-foreground/50 tracking-[0.2em] uppercase">
                      Featured
                    </span>
                  </div>

                  <h3 className="font-cormorant font-semibold text-3xl lg:text-4xl text-foreground tracking-[-0.01em]">
                    {featured.name}
                  </h3>

                  <p className="font-sans text-muted-foreground leading-relaxed">
                    {featured.description}
                  </p>

                  <p className="font-sans text-sm text-muted-foreground/70 leading-relaxed italic border-l border-[rgba(200,169,110,0.2)] pl-4">
                    {featured.detail}
                  </p>
                </div>

                <div className="space-y-6 lg:pt-2">
                  {/* Mini chart mockup */}
                  <div className="border border-[rgba(200,169,110,0.08)] rounded-sm p-4 space-y-2 font-mono text-[10px]">
                    <div className="flex justify-between text-muted-foreground/50 tracking-[0.1em] uppercase pb-2 border-b border-[rgba(200,169,110,0.06)]">
                      <span>NVDA</span>
                      <span>1Y · Daily</span>
                    </div>
                    {/* Simulated chart bars */}
                    <div className="flex items-end gap-0.5 h-14">
                      {[40,55,48,62,58,70,65,72,68,75,71,78,74,80,76,82].map((h, i) => (
                        <div
                          key={i}
                          className="flex-1 rounded-sm transition-all"
                          style={{
                            height: `${h}%`,
                            background: i > 11
                              ? "rgba(200,169,110,0.5)"
                              : "rgba(200,169,110,0.15)",
                          }}
                        />
                      ))}
                    </div>
                    <div className="flex justify-between text-muted-foreground/30 pt-1">
                      <span>Stop loss: $847.20</span>
                      <span className="text-accent/60">ATR-based · 2×</span>
                    </div>
                  </div>

                  {/* Tech tags */}
                  <div className="flex flex-wrap gap-2">
                    {featured.tech.map((tag) => (
                      <span
                        key={tag}
                        className="font-mono text-[10px] text-muted-foreground/60 tracking-[0.12em] uppercase border border-[rgba(150,150,150,0.1)] px-2 py-0.5 rounded-sm"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  <ToolButton href={featured.href} status={featured.status} />
                </div>
              </div>
            </motion.div>

            {/* Secondary cards — 3-col at lg */}
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              {secondary.map((tool, i) => (
                <motion.div
                  key={tool.id}
                  initial={{ opacity: 0, y: 30 }}
                  animate={isInView ? { opacity: 1, y: 0 } : {}}
                  transition={{ duration: 0.8, delay: 0.35 + 0.08 * i, ease: [0.16, 1, 0.3, 1] }}
                  className={cn(
                    "group flex flex-col border transition-all duration-500 p-7 space-y-5",
                    tool.tagAccent
                      ? "border-[rgba(200,169,110,0.18)] hover:border-[rgba(200,169,110,0.35)]"
                      : "border-[rgba(200,169,110,0.08)] hover:border-[rgba(200,169,110,0.22)]"
                  )}
                  style={{ background: "#0E1014" }}
                >
                  <div className="flex items-center gap-3">
                    <span className={cn(
                      "font-mono text-[10px] tracking-[0.2em] uppercase px-2.5 py-1 rounded-sm border",
                      tool.tagAccent
                        ? "text-accent border-[rgba(200,169,110,0.3)]"
                        : "text-muted-foreground/60 border-[rgba(150,150,150,0.12)]"
                    )}>
                      {tool.tag}
                    </span>
                  </div>

                  <h3 className="font-cormorant font-semibold text-2xl text-foreground tracking-[-0.01em]">
                    {tool.name}
                  </h3>

                  <p className="font-sans text-sm text-muted-foreground leading-relaxed flex-1">
                    {tool.description}
                  </p>

                  <div className="flex flex-wrap gap-2">
                    {tool.tech.map((tag) => (
                      <span
                        key={tag}
                        className="font-mono text-[10px] text-muted-foreground/50 tracking-[0.12em] uppercase border border-[rgba(150,150,150,0.08)] px-2 py-0.5 rounded-sm"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>

                  <ToolButton href={tool.href} status={tool.status} />
                </motion.div>
              ))}
            </div>

          </div>
        </div>
      </div>
    </section>
  )
}

function ToolButton({ href, status }: { href: string; status: string }) {
  const isPlaceholder = href.startsWith("STREAMLIT_URL")

  return isPlaceholder ? (
    <div className="inline-flex items-center gap-2 font-mono text-[11px] text-muted-foreground/40 tracking-[0.2em] uppercase cursor-default">
      <span className="w-1.5 h-1.5 rounded-full border border-muted-foreground/30" />
      {status}
    </div>
  ) : (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="group/btn inline-flex items-center gap-2 font-mono text-[11px] text-accent tracking-[0.2em] uppercase hover:text-foreground transition-colors duration-300"
    >
      <span>Launch tool</span>
      <span className="group-hover/btn:translate-x-1 transition-transform duration-300">→</span>
    </a>
  )
}
